name: lacrei_app
description: Um projeto para a campanha Lacrei nas Escolas.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  introduction_screen: ^3.1.14
  shared_preferences: ^2.2.3
  http: ^1.2.1
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  flutter_animate: ^4.5.0
  flutter_tilt: ^3.2.3
  font_awesome_flutter: ^10.7.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.4
  cloud_functions: ^4.6.0
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.7
  image_picker: ^1.1.2
  image_cropper: ^7.0.5
  google_maps_flutter: ^2.9.0
  url_strategy: ^0.2.0
  google_maps_flutter_web: ^0.5.4+2
  csv: ^5.1.1 
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/assets/
  - assets/animations/
  - assets/mp4-unscreen.gif
