// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYyfrC0Y3iQcK73l4jSXdCyDaW9xHKwDk',
    appId: '1:103402952377:web:0d0a77fa1c37885731ad68',
    messagingSenderId: '103402952377',
    projectId: 'lacrei-app-escolas',
    authDomain: 'lacrei-app-escolas.firebaseapp.com',
    storageBucket: 'lacrei-app-escolas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnMZ0UzFYMwaD9QYa5KPXJh-rGx4gV53Q',
    appId: '1:103402952377:android:79013c607b7aa26031ad68',
    messagingSenderId: '103402952377',
    projectId: 'lacrei-app-escolas',
    storageBucket: 'lacrei-app-escolas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh05E5VINONIYEy3oZXSgizTprpd48ZFk',
    appId: '1:103402952377:ios:baddecdfaab5bef231ad68',
    messagingSenderId: '103402952377',
    projectId: 'lacrei-app-escolas',
    storageBucket: 'lacrei-app-escolas.firebasestorage.app',
    iosBundleId: 'com.example.lacreiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh05E5VINONIYEy3oZXSgizTprpd48ZFk',
    appId: '1:103402952377:ios:baddecdfaab5bef231ad68',
    messagingSenderId: '103402952377',
    projectId: 'lacrei-app-escolas',
    storageBucket: 'lacrei-app-escolas.firebasestorage.app',
    iosBundleId: 'com.example.lacreiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYyfrC0Y3iQcK73l4jSXdCyDaW9xHKwDk',
    appId: '1:103402952377:web:f2cbbc618cc02b1e31ad68',
    messagingSenderId: '103402952377',
    projectId: 'lacrei-app-escolas',
    authDomain: 'lacrei-app-escolas.firebaseapp.com',
    storageBucket: 'lacrei-app-escolas.firebasestorage.app',
  );
}
